development:
  adapter: postgresql
  encoding: unicode
  database: spelunkular_development
  pool: 5
  host: localhost
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: spelunkular_production
  pool: 5
  host: localhost
  username: postgres
  password: 
